In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("/content/diabetes.csv")

In [6]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
df.shape

(768, 9)

In [9]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [10]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [13]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [15]:
# to know about the datset fully
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [18]:
# to find the missisng value
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [24]:
# to find the duplicate values in the dataset
df.duplicated().sum()

np.int64(0)

In [25]:
# to finmd the unique values
df.nunique()

Pregnancies                  17
Glucose                     136
BloodPressure                47
SkinThickness                51
Insulin                     186
BMI                         248
DiabetesPedigreeFunction    517
Age                          52
Outcome                       2
dtype: int64

In [28]:
# to check the invalis zero values
(df[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']]==0).sum()

Glucose            5
BloodPressure     35
SkinThickness    227
Insulin          374
BMI               11
dtype: int64

In [29]:
# for selecting and filterimg
# select only thge single column
df['Glucose']

0      148
1       85
2      183
3       89
4      137
      ...
763    101
764    122
765    121
766    126
767     93
Name: Glucose, Length: 768, dtype: int64

In [31]:
# to select the multiple columns
df[['Glucose','BMI','Age']]

     Glucose   BMI  Age
0        148  33.6   50
1         85  26.6   31
2        183  23.3   32
3         89  28.1   21
4        137  43.1   33
..       ...   ...  ...
763      101  32.9   63
764      122  36.8   27
765      121  26.2   30
766      126  30.1   47
767       93  30.4   23

[768 rows x 3 columns]

In [32]:
# to filter the rows with the help of columns
df[df['Age']>50]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
...,...,...,...,...,...,...,...,...,...
719,5,97,76,27,0,35.6,0.378,52,1
734,2,105,75,0,0,23.3,0.560,53,0
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
763,10,101,76,48,180,32.9,0.171,63,0

In [34]:
# to filter with multiple condition
df[(df['Age']>50) & (df['Outcome']==1)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
24,11,143,94,33,146,36.6,0.254,51,1
39,4,111,72,47,207,37.1,1.390,56,1
43,9,171,110,24,240,45.4,0.721,54,1
53,8,176,90,34,300,33.7,0.467,58,1
93,4,134,72,0,0,23.8,0.277,60,1
115,4,146,92,0,0,31.2,0.539,61,1
129,0,105,84,0,0,27.9,0.741,62,1
186,8,181,68,36,495,30.1,0.615,60,1
206,8,196,76,29,280,37.5,0.605,57,1
207,5,162,104,0,0,37.7,0.151,52,1
221,2,158,90,0,0,31.6,0.805,66,1
236,7,181,84,21,192,35.9,0.586,51,1
259,11,155,76,28,150,33.3,1.353,51,1
284,2,108,80,0,0,27.0,0.259,52,1
319,6,194,78,0,0,23.5,0.129,59,1
363,4,146,78,0,0,38.5,0.520,67,1
375,12,140,82,43,325,39.2,0.528,58,1
388,5,144,82,26,285,32.0,0.452,58,1
458,10,148,84,48,237,37.6,1.001,51,1
498,7,195,70,33,145,25.1,0.163,55,1
516,9,145,88,34,165,30.3,0.771,53,1
542,10,90,85,32,0,34.9,0.825,56,1
546,5,187,76,27,207,43.6,1.034,53,1
560,6,125,76,0,0,33.8,0.121,54,1
579,2,197,70,99,0,34.7,0.575,62,1
584,8,124,76,24,600,28.7,0.687,52,1
588,3,176,86,27,156,33.3,1.154,52,1
603,7,150,78,29,126,35.2,0.692,54,1
666,4,145,82,18,0,32.5,0.235,70,1
676,9,156,86,0,0,24.8,0.230,53,1
702,1,168,88,29,0,35.0,0.905,52,1
719,5,97,76,27,0,35.6,0.378,52,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1

In [36]:
# to access rows by index
df.iloc[100:105]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
100,1,163,72,0,0,39.0,1.222,33,1
101,1,151,60,0,0,26.1,0.179,22,0
102,0,125,96,0,0,22.5,0.262,21,0
103,1,81,72,18,40,26.6,0.283,24,0
104,2,85,65,0,0,39.6,0.930,27,0

In [38]:
 # sorting and grouping
 df.sort_values(by='Age',ascending=False).head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
459,9,134,74,33,60,25.9,0.460,81,0
453,2,119,0,0,0,19.6,0.832,72,0
666,4,145,82,18,0,32.5,0.235,70,1
684,5,136,82,0,0,0.0,0.640,69,0
123,5,132,80,0,0,26.8,0.186,69,0

In [39]:
# with value count
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64